name: Release

on:
  push:
    tags: ['*']

jobs:
  init:
    runs-on: [ X64 ]
    outputs:
      branch: ${{ steps.vars.outputs.branch }}
      tag: ${{ steps.vars.outputs.tag }}
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v3
      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=tag;]$(echo ${GITHUB_REF/refs\/tags\//})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  alpine:
    needs:
      - init
    uses: ./.github/workflows/docker-tag.yml
    secrets: inherit
    with:
      distro: alpine
      tag: ${GITHUB_REF/refs\/tags\//}
  debian:
    needs:
      - init
    uses: ./.github/workflows/docker-tag.yml
    secrets: inherit
    with:
      distro: debian
      tag: ${GITHUB_REF/refs\/tags\//}
